name: Build & Test

on:
  push:
    branches:
      - main
      - canary
      - beta
      - stable
      - v[0-9]+.[0-9]+.x-staging
      - v[0-9]+.[0-9]+.x
    paths-ignore:
      - README.md
  pull_request:
  merge_group:

env:
  DEBUG: napi:*
  BUILD_TYPE: canary
  APP_NAME: nota
  NOTA_ENV: dev
  COVERAGE: true
  MACOSX_DEPLOYMENT_TARGET: '14.0'
  DEPLOYMENT_TYPE: nota
  NOTA_INDEXER_ENABLED: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=14384
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript', 'typescript']
        project: ['nota', 'blocksuite']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          source-root: ${{ matrix.project == 'nota' && '.' || 'blocksuite' }}

      - name: Delete blocksuite before codeql analysis
        if: ${{ matrix.project == 'nota' }}
        run: rm -rf blocksuite

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7
      - name: Setup Go (for actionlint)
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
      - name: Install actionlint
        shell: bash
        run: |
          set -euo pipefail
          go install github.com/rhysd/actionlint/cmd/actionlint@v1.7.11
      - name: Run actionlint
        shell: bash
        run: |
          set -euo pipefail
          "$(go env GOPATH)/bin/actionlint"
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          electron-install: false
          full-cache: true
      - name: Run oxlint
        run: yarn lint:ox
      - name: Run i18n codegen
        run: yarn nota @nota/i18n build
      - name: Run ESLint
        run: yarn lint:eslint --max-warnings=0
      - name: Run Prettier
        # Set nmMode in `actions/setup-node` will modify the .yarnrc.yml
        run: |
          git checkout .yarnrc.yml
          yarn lint:prettier
      - name: Yarn Dedupe
        run: yarn dedupe --check

  typecheck:
    name: Typecheck
    runs-on: ubuntu-24.04-arm
    env:
      NODE_OPTIONS: --max-old-space-size=14384
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          electron-install: false
          full-cache: true
      - name: Run i18n codegen
        run: yarn nota @nota/i18n build
      - name: Run Type Check
        run: yarn typecheck
      - name: Run BS Docs Build
        run: |
          yarn nota bs-docs build
          git checkout packages/frontend/i18n/src/i18n-completenesses.json
          if git status --porcelain | grep -q .; then
            echo "Run 'yarn typecheck && yarn nota bs-docs build' and make sure all changes are submitted"
            exit 1
          else
            echo "All changes are submitted"
          fi

  rust-test-filter:
    name: Rust test filter
    runs-on: ubuntu-latest
    outputs:
      run-rust: ${{ steps.rust-filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v7

      - uses: dorny/paths-filter@v4
        id: rust-filter
        with:
          filters: |
            rust:
              - '**/*.rs'
              - '**/Cargo.toml'
              - '**/Cargo.lock'
              - '.cargo/**'
              - 'rust-toolchain*'
              - '.github/actions/build-rust/**'

  lint-rust:
    name: Lint Rust
    if: ${{ needs.rust-test-filter.outputs.run-rust == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - rust-test-filter
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/build-rust
        with:
          target: x86_64-unknown-linux-gnu
          package: 'nota'
          no-build: 'true'
      - name: fmt check
        run: |
          rustup toolchain add nightly
          rustup component add --toolchain nightly-x86_64-unknown-linux-gnu rustfmt
          cargo +nightly fmt --all -- --check
      - name: Clippy
        run: |
          rustup component add clippy
          cargo clippy --workspace --all-targets --all-features -- -D warnings

  check-git-status:
    name: Check Git Status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          full-cache: true

      - name: Run Check
        run: |
          yarn nota init
          yarn workspace @nota/graphql check
          yarn nota i18n build
          git checkout packages/frontend/i18n/src/i18n-completenesses.json
          if git status --porcelain | grep -q .; then
            echo "Run 'yarn nota init && yarn workspace @nota/graphql check && yarn nota i18n build' and make sure all changes are submitted"
            exit 1
          else
            echo "All changes are submitted"
          fi

  check-yarn-binary:
    name: Check yarn binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run check
        run: |
          set -euo pipefail
          yarn_version="$(node -e "console.log(require('./package.json').packageManager.split('@')[1])")"
          yarn set version "$yarn_version"
          git diff --exit-code

  e2e-blocksuite-test:
    name: E2E BlockSuite Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/monorepo @nota-test/blocksuite @blocksuite/playground @blocksuite/integration-test
          playwright-install: true
          playwright-platform: 'chromium'
          electron-install: false
          full-cache: true

      - name: Run playground build
        run: yarn workspace @blocksuite/playground build

      - name: Run playwright tests
        run: yarn workspace @nota-test/blocksuite test --forbid-only --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-e2e-bs-${{ matrix.shard }}
          path: ./test-results
          if-no-files-found: ignore

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-24.04-arm
    env:
      DISTRIBUTION: web
      IN_CI_TEST: true
      NODE_OPTIONS: --max-old-space-size=14384
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/monorepo @nota-test/nota-local @nota/web
          playwright-install: true
          playwright-platform: 'chromium'
          electron-install: false
          full-cache: true

      - name: Run playwright tests
        run: yarn nota @nota-test/nota-local e2e --forbid-only --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-e2e-${{ matrix.shard }}
          path: ./test-results
          if-no-files-found: ignore

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs:
      - build-native-linux
    env:
      DISTRIBUTION: web
    strategy:
      fail-fast: false
      matrix:
        shard: [1, 2, 3, 4, 5]
    steps:
      - uses: actions/checkout@v7
      - name: Install tool integration prerequisites
        run: sudo apt-get update && sudo apt-get install -y ripgrep
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          electron-install: true
          playwright-install: true
          playwright-platform: 'chromium,firefox,webkit'
          full-cache: true

      - name: Download nota.linux-x64-gnu.node
        uses: actions/download-artifact@v7
        with:
          name: nota.linux-x64-gnu.node
          path: ./packages/frontend/native

      - name: Unit Test
        run: yarn test:coverage --shard=${{ matrix.shard }}/${{ strategy.job-total }}

      - name: Upload unit test coverage results
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./.coverage/store/lcov.info
          flags: unittest
          name: nota
          fail_ci_if_error: false

  build-native-linux:
    name: Build Nota native (x86_64-unknown-linux-gnu)
    runs-on: ubuntu-latest
    env:
      CARGO_PROFILE_RELEASE_DEBUG: '1'
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/native
          electron-install: false
      - name: Setup filename
        id: filename
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          PLATFORM_ARCH_ABI="$(node -e "console.log(require('@napi-rs/cli').parseTriple('x86_64-unknown-linux-gnu').platformArchABI)")"
          echo "filename=nota.$PLATFORM_ARCH_ABI.node" >> "$GITHUB_OUTPUT"
      - name: Build Nota native
        uses: ./.github/actions/build-rust
        with:
          target: x86_64-unknown-linux-gnu
          package: '@nota/native'
      - name: Upload ${{ steps.filename.outputs.filename }}
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ steps.filename.outputs.filename }}
          path: ${{ github.workspace }}/packages/frontend/native/${{ steps.filename.outputs.filename }}
          if-no-files-found: error

  build-native-macos:
    name: Build Nota native (${{ matrix.spec.target }})
    runs-on: ${{ matrix.spec.os }}
    env:
      CARGO_PROFILE_RELEASE_DEBUG: '1'
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: macos-latest, target: aarch64-apple-darwin }

    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/native
          electron-install: false
      - name: Setup filename
        id: filename
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          PLATFORM_ARCH_ABI="$(node -e "console.log(require('@napi-rs/cli').parseTriple('${{ matrix.spec.target }}').platformArchABI)")"
          echo "filename=nota.$PLATFORM_ARCH_ABI.node" >> "$GITHUB_OUTPUT"
      - name: Build Nota native
        uses: ./.github/actions/build-rust
        with:
          target: ${{ matrix.spec.target }}
          package: '@nota/native'
      - name: Upload ${{ steps.filename.outputs.filename }}
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ steps.filename.outputs.filename }}
          path: ${{ github.workspace }}/packages/frontend/native/${{ steps.filename.outputs.filename }}
          if-no-files-found: error

  # Split Windows build because it's too slow
  # and other ci jobs required linux native
  build-native-windows:
    name: Build Nota native (${{ matrix.spec.target }})
    runs-on: ${{ matrix.spec.os }}
    env:
      CARGO_PROFILE_RELEASE_DEBUG: '1'
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
          - { os: windows-latest, target: aarch64-pc-windows-msvc }

    steps:
      - uses: actions/checkout@v7
      - uses: samypr100/setup-dev-drive@v4
        with:
          workspace-copy: true
          drive-size: 8GB
          drive-format: NTFS
          env-mapping: |
            CARGO_HOME,{{ DEV_DRIVE }}/.cargo
            RUSTUP_HOME,{{ DEV_DRIVE }}/.rustup
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/native
          electron-install: false
      - name: Setup filename
        id: filename
        working-directory: ${{ env.DEV_DRIVE_WORKSPACE }}
        shell: bash
        run: |
          PLATFORM_ARCH_ABI="$(node -e "console.log(require('@napi-rs/cli').parseTriple('${{ matrix.spec.target }}').platformArchABI)")"
          echo "filename=nota.$PLATFORM_ARCH_ABI.node" >> "$GITHUB_OUTPUT"
      - name: Build Nota native
        uses: ./.github/actions/build-rust
        with:
          target: ${{ matrix.spec.target }}
          package: '@nota/native'
      - name: Upload ${{ steps.filename.outputs.filename }}
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: ${{ steps.filename.outputs.filename }}
          path: ${{ env.DEV_DRIVE_WORKSPACE }}/packages/frontend/native/${{ steps.filename.outputs.filename }}
          if-no-files-found: error

  build-electron-renderer:
    name: Build @nota/electron renderer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota/monorepo @nota/electron-renderer @nota/nbstore @nota/infra
          electron-install: false
          full-cache: true
      - name: Build Electron renderer
        run: yarn nota @nota/electron-renderer build
        env:
          DISTRIBUTION: desktop
      - name: zip web
        run: tar -czf dist.tar.gz --directory=packages/frontend/apps/electron-renderer/dist .
      - name: Upload web artifact
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: web
          path: dist.tar.gz
          if-no-files-found: error

  native-unit-test:
    name: Native Unit Test
    runs-on: ubuntu-latest
    needs:
      - build-native-linux
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          extra-flags: workspaces focus @nota-tools/cli @nota/monorepo @nota/native
          electron-install: false
      - name: Download nota.linux-x64-gnu.node
        uses: actions/download-artifact@v7
        with:
          name: nota.linux-x64-gnu.node
          path: ./packages/frontend/native
      - name: Unit Test
        run: yarn nota @nota/native test

  loom:
    name: loom thread test
    if: ${{ needs.rust-test-filter.outputs.run-rust == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - rust-test-filter
    env:
      RUSTFLAGS: --cfg loom
      RUST_BACKTRACE: full
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Install latest nextest release
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98

      - name: Loom Thread Test
        run: |
          cargo nextest run -p y-octo --lib

  rust-test:
    name: Run native tests
    if: ${{ needs.rust-test-filter.outputs.run-rust == 'true' }}
    runs-on: ubuntu-latest
    needs:
      - rust-test-filter
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v7
      - name: Setup Rust
        uses: ./.github/actions/build-rust
        with:
          target: x86_64-unknown-linux-gnu
          package: 'nota'
          no-build: 'true'

      - name: Install latest nextest release
        uses: taiki-e/install-action@v2
        with:
          tool: nextest@0.9.98

      - name: Run tests
        run: cargo nextest run --workspace --features use-as-lib --release --no-fail-fast

  desktop-test:
    name: Desktop Test (${{ matrix.spec.os }}, ${{ matrix.spec.platform }}, ${{ matrix.spec.arch }}, ${{ matrix.spec.target }}, ${{ matrix.spec.test }})
    runs-on: ${{ matrix.spec.os }}
    needs:
      - build-electron-renderer
      - build-native-linux
      - build-native-macos
      - build-native-windows
    strategy:
      fail-fast: false
      matrix:
        spec:
          - {
              os: macos-latest,
              platform: macos,
              arch: x64,
              target: x86_64-apple-darwin,
              test: false,
            }
          - {
              os: macos-latest,
              platform: macos,
              arch: arm64,
              target: aarch64-apple-darwin,
              test: true,
            }
          - {
              os: ubuntu-latest,
              platform: linux,
              arch: x64,
              target: x86_64-unknown-linux-gnu,
              test: true,
            }
          - {
              os: windows-latest,
              platform: windows,
              arch: x64,
              target: x86_64-pc-windows-msvc,
              test: true,
            }
    steps:
      - uses: actions/checkout@v7
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        timeout-minutes: 10
        with:
          extra-flags: workspaces focus @nota/electron @nota/ai-backend @nota/monorepo @nota-test/nota-desktop @nota/nbstore @nota/infra
          playwright-install: ${{ matrix.spec.test && 'true' || 'false' }}
          playwright-platform: 'chromium'
          hard-link-nm: false
          enableScripts: false

      - name: Setup filename
        id: filename
        shell: bash
        run: |
          PLATFORM_ARCH_ABI="$(node -e "console.log(require('@napi-rs/cli').parseTriple('${{ matrix.spec.target }}').platformArchABI)")"
          echo "filename=nota.$PLATFORM_ARCH_ABI.node" >> "$GITHUB_OUTPUT"

      - name: Download ${{ steps.filename.outputs.filename }}
        uses: actions/download-artifact@v7
        with:
          name: ${{ steps.filename.outputs.filename }}
          path: ./packages/frontend/native

      - name: Run unit tests
        if: ${{ matrix.spec.test }}
        shell: bash
        run: yarn nota @nota/electron vitest

      - name: Download web artifact
        uses: ./.github/actions/download-web
        with:
          path: packages/frontend/apps/electron/resources/web-static

      - name: Build Desktop Layers
        run: yarn nota @nota/electron build

      - name: Run desktop tests
        if: ${{ matrix.spec.os == 'ubuntu-latest' }}
        run: |
          # Workaround for Electron apps failing to initialize on Ubuntu 24.04 due to AppArmor restrictions
          # Disables unprivileged user namespaces restriction to allow Electron apps to run
          # Reference: https://github.com/electron/electron/issues/42510
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- yarn nota @nota-test/nota-desktop e2e

      - name: Run desktop tests
        if: ${{ matrix.spec.test && matrix.spec.os != 'ubuntu-latest' }}
        run: yarn nota @nota-test/nota-desktop e2e

      - name: Make bundle (macOS)
        if: ${{ matrix.spec.target == 'aarch64-apple-darwin' }}
        env:
          SKIP_BUNDLE: true
          SKIP_WEB_BUILD: true
          HOIST_NODE_MODULES: 1
        run: yarn nota @nota/electron package --platform=darwin --arch=arm64

      - name: Make Bundle (Windows)
        if: ${{ matrix.spec.target == 'x86_64-pc-windows-msvc' }}
        shell: bash
        env:
          SKIP_BUNDLE: true
          SKIP_WEB_BUILD: true
          HOIST_NODE_MODULES: 1
        run: |
          rm -rf packages/frontend/apps/electron/node_modules/@nota/nbstore/node_modules/@blocksuite/affine/node_modules
          rm -rf packages/frontend/apps/electron/node_modules/@nota/native/node_modules
          yarn nota @nota/electron package --platform=win32 --arch=x64

      - name: Make Bundle (Linux)
        run: |
          sudo add-apt-repository universe
          sudo apt install -y libfuse2 elfutils flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
          flatpak update
          # some flatpak deps need git protocol.file.allow
          git config --global protocol.file.allow always
          yarn nota @nota/electron make --platform=linux --arch=x64
        if: ${{ matrix.spec.target == 'x86_64-unknown-linux-gnu' }}
        env:
          SKIP_WEB_BUILD: 1
          HOIST_NODE_MODULES: 1

      - name: Output check
        if: ${{ matrix.spec.os == 'macos-latest' && matrix.spec.arch == 'arm64' }}
        run: |
          yarn nota @nota/electron node ./scripts/macos-arm64-output-check.ts

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: test-results-e2e-${{ matrix.spec.os }}-${{ matrix.spec.arch }}
          path: ./test-results
          if-no-files-found: ignore

  test-done:
    needs:
      - analyze
      - lint
      - typecheck
      - lint-rust
      - check-git-status
      - check-yarn-binary
      - e2e-test
      - e2e-blocksuite-test
      - unit-test
      - build-native-linux
      - build-native-macos
      - build-native-windows
      - build-electron-renderer
      - native-unit-test
      - loom
      - rust-test
      - rust-test-filter
      - desktop-test
    if: always()
    runs-on: ubuntu-latest
    name: CI passed
    steps:
      - run: exit 1
        # Thank you, next https://github.com/vercel/next.js/blob/canary/.github/workflows/build_and_test.yml#L379
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
